version: '3'

services:
    db:
        container_name: yegitek_mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "pass"
            MYSQL_DATABASE: "yegitek"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "pass"
        ports:
            - 3307:3306
        networks:
            - symfony
    php:
        container_name: yegitek_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www/
        networks:
            - symfony
    nginx:
        container_name: yegitek_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/
        ports:
            - 80:80
        networks:
            - symfony
volumes:
    db_app:

networks:
    symfony:
